package com.zhoujie.dao;

import java.sql.Connection;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.zhoujie.model.Comment;
import com.zhoujie.model.News;

public interface CommentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer commentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated
     */
    Comment selectByPrimaryKey(Integer commentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Comment record);
    
    int CommentCounts(@Param("nid")Integer nid, @Param("aDate")String aDate, @Param("bDate")String bDate);
    
    List<Comment> CommentList(@Param("nid")Integer nid, @Param("start")int start, @Param("pageSize")int pageSize, @Param("bDate")String bDate, @Param("aDate")String aDate);
    
    int commentDelete(@Param("commentIds")String commentIds);
 
}